name: Deploy to Webserver

on: 
  push:
      branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: pringon/diaspora-hub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run a command remotely
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          hosts: ec2-3-8-8-232.eu-west-2.compute.amazonaws.com
          user: ubuntu
          private_key: ${{ secrets.WEB_SERVER_PEM }}
          commands: docker kill diaspora-hub-server; docker run -ti --name diaspora-hub-server -p 80:80 pringon/diaspora-hub
